version: "3.7"

services:
  web:
    image: ghcr.io/keyword-scrapping-frontend/scrapping-web:prod
    depends_on:
      - app
    restart: always
    ports:
      - "3000:80"
    networks:
      - webnet

networks:
  webnet:
