name: PR-CI

on:
  pull_request:
    branches: ["main"]

permissions:
  actions: read
  contents: read

jobs:
  lint-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Check format
        run: npm run format:check

      - name: Check lint
        run: npm run lint:check

      - name: Verify tests
        run: npm run test:cov
